Update for catalog
BlueBrain/CoreNeuron pull request #686
Opened 2021-11-01 07:25 UTC by jamesgking

Minor edits to Funding information to make consistent with text used in other softwares released by Blue Brain Project

2021-11-01 07:27 UTC, pramodk approved these changes
LGTM

2021-11-01 08:44 UTC, iomaganaris commented
please retest

2021-11-01 08:48 UTC, ohm314 requested changes
I think just this minor fix is needed

2021-11-01 08:48 UTC, ohm314 commented on README.md
> +CoreNEURON is developed in a joint collaboration between the Blue Brain Project and Yale University. This work was supported by funding to the Blue Brain Project, a research center of the École polyt
```suggestion
CoreNEURON is developed in a joint collaboration between the Blue Brain Project and Yale University. This work is supported by funding to the Blue Brain Project, a research center of the École polytechnique fédérale de Lausanne (EPFL), from the Swiss government’s ETH Board of the Swiss Federal Institutes of Technology, NIH grant number R01NS11613 (Yale University), the European Union Seventh Framework Program (FP7/20072013) under grant agreement n◦ 604102 (HBP) and the European Union’s Horizon 2020 Framework Programme for Research and Innovation under Specific Grant Agreement n◦ 720270 (Human Brain Project SGA1), n◦ 785907 (Human Brain Project SGA2) and n◦ 945539 (Human Brain Project SGA3).
```

2021-11-09 09:14 UTC, ohm314 approved these changes
lgtm

2021-11-19 14:08 UTC, merged